// Self-contained HTML triage report. No external assets, all CSS inline,
// double-clickable from the desktop.
//
// Layout: repo first, then bucket sections within each repo. Per the RFC,
// the four high-signal buckets default expanded; CODEOWNERS/FYI/Hidden
// default collapsed. Empty buckets are omitted entirely.

import {
  BUCKETS_EXPANDED_BY_DEFAULT,
  BUCKET_LABELS,
  type Bucket,
  type ClassifiedPR,
} from '../buckets.js';
import { type BucketSection, formatAge, groupByRepo, type RepoBlock } from './shared.js';

export interface RenderOptions {
  viewer: string;
  now: Date;
  authorOpenCounts: Map<string, Map<string, number>>; // repo -> author -> count
}

export function renderHtml(classified: ClassifiedPR[], opts: RenderOptions): string {
  const blocks = groupByRepo(classified);
  const date = opts.now.toISOString().slice(0, 16).replace('T', ' ');

  const body = blocks
    .map((b) => renderRepoBlock(b, opts.viewer, opts.now, opts.authorOpenCounts.get(b.repo)))
    .join('\n');

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>PR Triage — ${escape(date)} — @${escape(opts.viewer)}</title>
<style>${CSS}</style>
</head>
<body>
<header>
  <h1>PR Triage</h1>
  <div class="meta">${escape(date)} UTC &middot; @${escape(opts.viewer)}</div>
</header>
${body}
<footer>Generated by <code>maintainer-tools triage</code>.</footer>
</body>
</html>
`;
}

function renderRepoBlock(
  block: RepoBlock,
  viewer: string,
  now: Date,
  counts: Map<string, number> | undefined,
): string {
  const sections = block.sections.map((s) =>
    renderSection(s, block.repo, viewer, now, counts ?? new Map()),
  );
  const repoUrl = `https://github.com/${block.repo}`;
  return `<section class="repo">
  <h2><a href="${repoUrl}">${escape(block.repo)}</a> <span class="count">${block.visibleCount} / ${block.totalCount} visible</span></h2>
  ${sections.join('\n  ')}
</section>`;
}

function renderSection(
  section: BucketSection,
  repo: string,
  viewer: string,
  now: Date,
  counts: Map<string, number>,
): string {
  const expanded = BUCKETS_EXPANDED_BY_DEFAULT.has(section.bucket) ? ' open' : '';
  const label = BUCKET_LABELS[section.bucket];
  const count = section.prs.length;

  if (section.bucket === 'hidden') {
    // Hidden bucket renders as count + breakdown, no individual rows.
    return renderHiddenSection(section, label, count);
  }

  const rows = section.prs.map((c) => renderRow(c, viewer, now, counts)).join('\n      ');
  void repo; // unused; reserved for per-repo link templating
  return `<details class="bucket bucket-${section.bucket}"${expanded}>
    <summary>${escape(label)} <span class="count">(${count})</span></summary>
    <table>
      <thead><tr><th>#</th><th>diff</th><th>title</th><th>author</th><th>flags</th><th>age</th></tr></thead>
      <tbody>
      ${rows}
      </tbody>
    </table>
  </details>`;
}

function renderHiddenSection(section: BucketSection, label: string, count: number): string {
  return `<details class="bucket bucket-hidden">
    <summary>${escape(label)} <span class="count">(${count})</span></summary>
    <p class="hidden-note">PRs in this bucket aren't actionable until the contributor moves: waiting-for-author, drafts, bot-authored. Listed here for completeness.</p>
  </details>`;
}

function renderRow(
  c: ClassifiedPR,
  viewer: string,
  now: Date,
  counts: Map<string, number>,
): string {
  const pr = c.pr;
  const diff = `<span class="diff"><span class="add">+${pr.additions}</span>/<span class="del">-${pr.deletions}</span></span>`;
  const author = pr.author?.login ?? '(unknown)';
  const openCount = counts.get(author) ?? 1;
  const authorTag = author === viewer ? ' <span class="role-tag">you</span>' : '';
  const flags = c.flags.map((f) => `<span class="flag flag-${f}">${escape(f)}</span>`).join(' ');
  const age = formatAge(pr, now);
  return `<tr>
        <td><a href="${pr.url}">#${pr.number}</a></td>
        <td>${diff}</td>
        <td>${escape(pr.title)}</td>
        <td><a href="https://github.com/${escape(author)}">@${escape(author)}</a>${authorTag} <span class="open-count">[${openCount} open]</span></td>
        <td>${flags}</td>
        <td>${escape(age)}</td>
      </tr>`;
}

const CSS = `
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; max-width: 1200px; margin: 2em auto; padding: 0 1em; color: #1f2328; line-height: 1.4; }
  header h1 { margin: 0 0 0.2em 0; }
  header .meta { color: #57606a; font-size: 0.9em; margin-bottom: 1.5em; }
  section.repo { margin: 2em 0; }
  section.repo > h2 { border-bottom: 1px solid #d0d7de; padding-bottom: 0.3em; }
  section.repo .count { font-weight: normal; color: #57606a; font-size: 0.85em; }
  details.bucket { margin: 0.5em 0; border-left: 3px solid #d0d7de; padding-left: 0.8em; }
  details.bucket-review-requested-on-you { border-left-color: #d29922; }
  details.bucket-youre-the-bottleneck { border-left-color: #cf222e; }
  details.bucket-high-trust-awaiting-first-response { border-left-color: #1f883d; }
  details.bucket-first-timer-awaiting { border-left-color: #8250df; }
  details.bucket-codeowners-hits, details.bucket-fyi, details.bucket-hidden { border-left-color: #d0d7de; }
  summary { cursor: pointer; padding: 0.3em 0; font-weight: 600; }
  summary .count { font-weight: normal; color: #57606a; }
  table { border-collapse: collapse; width: 100%; margin: 0.5em 0 1em 0; font-size: 0.9em; }
  th, td { padding: 0.3em 0.5em; text-align: left; vertical-align: top; }
  thead { color: #57606a; font-size: 0.85em; }
  tbody tr { border-top: 1px solid #eaeef2; }
  tbody tr:hover { background: #f6f8fa; }
  td a { color: #0969da; text-decoration: none; }
  td a:hover { text-decoration: underline; }
  .diff .add { color: #1f883d; }
  .diff .del { color: #cf222e; }
  .role-tag { font-size: 0.7em; background: #ddf4ff; color: #0969da; padding: 0.05em 0.4em; border-radius: 3px; vertical-align: middle; }
  .open-count { color: #57606a; font-size: 0.85em; }
  .flag { font-size: 0.7em; padding: 0.1em 0.4em; border-radius: 3px; background: #eaeef2; margin-right: 0.2em; }
  .flag-BLOCKER { background: #cf222e; color: white; }
  .flag-CONFLICT { background: #ffebe9; color: #82071e; }
  .flag-STALE { background: #fff8c5; color: #66533d; }
  .flag-QUESTION { background: #ddf4ff; color: #0550ae; }
  .flag-POSSIBLE-QUESTION { background: #fff1e5; color: #66533d; }
  .flag-DRAFT, .flag-BOT { background: #eaeef2; color: #57606a; }
  .hidden-note { color: #57606a; font-size: 0.85em; margin: 0.5em 0; }
  footer { margin-top: 4em; color: #8b949e; font-size: 0.8em; border-top: 1px solid #eaeef2; padding-top: 1em; }
`;

const ESCAPE_MAP: Record<string, string> = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#39;',
};

function escape(s: string): string {
  return String(s).replace(/[&<>"']/g, (c) => ESCAPE_MAP[c] ?? c);
}
