// Self-contained HTML triage report. No external assets, all CSS inline,
// double-clickable from the desktop.
//
// Layout: repo first, then (optionally) priority groups, then bucket sections.
// Per the RFC, the four high-signal buckets default expanded; CODEOWNERS/FYI/
// Hidden default collapsed. Empty buckets are omitted entirely.

import {
  computeComposition,
  FILE_CLASSES,
  issueUrl,
  parseRefKey,
  refKey,
  type FileClass,
  type PullRequest,
} from '@jaegertracing/maintainer-tools-checks';
import {
  BUCKETS_EXPANDED_BY_DEFAULT,
  BUCKET_DESCRIPTIONS,
  BUCKET_LABELS,
  BUCKET_ORDER,
  type Bucket,
  type ClassifiedPR,
} from '../buckets.js';
import {
  type BucketSection,
  formatAge,
  groupByRepo,
  type PriorityGroup,
  type RepoBlock,
} from './shared.js';

// All outbound links (repo, PR, author) open in a new tab so following one
// doesn't lose the maintainer's place in the report.
const NEW_TAB = 'target="_blank" rel="noopener noreferrer"';

export interface RenderOptions {
  viewer: string;
  now: Date;
  authorOpenCounts: Map<string, Map<string, number>>; // repo -> author -> count
  priorityLabels?: string[];
}

export function renderHtml(classified: ClassifiedPR[], opts: RenderOptions): string {
  const blocks = groupByRepo(classified, opts.priorityLabels);
  const date = opts.now.toISOString().slice(0, 16).replace('T', ' ');

  const summary = renderSummary(blocks);
  const body = blocks
    .map((b) => renderRepoBlock(b, opts.viewer, opts.now, opts.authorOpenCounts.get(b.repo)))
    .join('\n');

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>PR Triage — ${escape(date)} — @${escape(opts.viewer)}</title>
<link rel="icon" type="image/svg+xml" href="${FAVICON_DATA_URL}">
<style>${CSS}</style>
</head>
<body>
<header>
  <h1>PR Triage</h1>
  <div class="meta">${escape(date)} UTC &middot; @${escape(opts.viewer)}</div>
  <div class="toolbar">
    <button type="button" id="expand-all">Expand All</button>
    <button type="button" id="collapse-all">Collapse All</button>
  </div>
</header>
${summary}
${body}
<footer>Generated by <code>maintainer-tools triage</code>.</footer>
<script>
  // Expand/collapse every <details> (bucket sections and priority groups)
  // in one click, so in-page browser search (Ctrl/Cmd+F) can reach text
  // inside sections that default to collapsed.
  document.getElementById('expand-all').addEventListener('click', () => {
    document.querySelectorAll('details').forEach((d) => { d.open = true; });
  });
  document.getElementById('collapse-all').addEventListener('click', () => {
    document.querySelectorAll('details').forEach((d) => { d.open = false; });
  });

  // Summary-table links point at sections that are often inside a collapsed
  // <details>. Browsers vary on whether a fragment navigation opens the
  // ancestors, and a link into a closed section otherwise scrolls nowhere, so
  // open the whole chain first and then scroll.
  document.querySelectorAll('.summary-table a[href^="#"]').forEach((a) => {
    a.addEventListener('click', (e) => {
      const target = document.getElementById(a.getAttribute('href').slice(1));
      if (!target) return;
      e.preventDefault();
      for (let n = target; n; n = n.parentElement) {
        if (n.tagName === 'DETAILS') n.open = true;
      }
      target.scrollIntoView({ block: 'start', behavior: 'smooth' });
      history.replaceState(null, '', a.getAttribute('href'));
    });
  });
</script>
</body>
</html>
`;
}

function slug(s: string): string {
  return s.replace(/[^A-Za-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

function repoAnchor(repo: string): string {
  return `repo-${slug(repo)}`;
}

// Anchor for one rendered bucket table. Derived from the same three values the
// renderer uses to place it, so a summary link and its section cannot drift.
// `group` is the priority-group label, or '' in the flat (no priorityLabels)
// view.
function sectionAnchor(repo: string, group: string, bucket: Bucket): string {
  return `s-${slug(repo)}-${group ? `${slug(group)}-` : ''}${bucket}`;
}

// Where a single summary cell's PRs actually live. With priorityLabels
// configured, one (repo, bucket) count is spread across a bucket table inside
// each priority group, so a cell has several targets rather than one.
interface CellTargets {
  count: number;
  parts: Array<{ group: string; count: number; anchor: string }>;
}

function cellTargets(block: RepoBlock, bucket: Bucket): CellTargets {
  const parts: CellTargets['parts'] = [];
  if (block.priorityGroups.length > 0) {
    for (const g of block.priorityGroups) {
      const s = g.sections.find((x) => x.bucket === bucket);
      if (s && s.prs.length > 0) {
        parts.push({
          group: g.label,
          count: s.prs.length,
          anchor: sectionAnchor(block.repo, g.label, bucket),
        });
      }
    }
  } else {
    const s = block.sections.find((x) => x.bucket === bucket);
    if (s && s.prs.length > 0) {
      parts.push({ group: '', count: s.prs.length, anchor: sectionAnchor(block.repo, '', bucket) });
    }
  }
  return { count: parts.reduce((a, p) => a + p.count, 0), parts };
}

// Bucket-by-repo matrix at the top of the report: how much is waiting, and
// where. The per-repo headings below already say "N / M visible", but nothing
// showed the shape of the queue across repos in one place.
//
// The total row counts visible buckets only. Blocked-on-author is listed under
// it, outside the total, because it is the bucket the report exists to exclude
// — folding it in would make the headline number the size of the whole queue
// rather than the size of the work.
function renderSummary(blocks: RepoBlock[]): string {
  if (blocks.length === 0) return '';
  const visibleBuckets = BUCKET_ORDER.filter((b) => b !== 'hidden');

  // A cell links to the first section holding its PRs. When the count spans
  // several priority groups the tooltip names the split, so the number a
  // reader jumps into is never silently smaller than the one they clicked.
  const cell = (block: RepoBlock, bucket: Bucket): string => {
    const { count, parts } = cellTargets(block, bucket);
    if (count === 0) return '<td class="zero">0</td>';
    const first = parts[0]!;
    const tip =
      parts.length > 1
        ? ` data-tip="${escape(parts.map((p) => `${p.group}: ${p.count}`).join(' · '))}"`
        : '';
    return `<td><a href="#${first.anchor}"${tip}>${count}</a></td>`;
  };

  const rowTotal = (bucket: Bucket): number =>
    blocks.reduce((a, b) => a + cellTargets(b, bucket).count, 0);

  const rows = visibleBuckets
    .filter((bucket) => rowTotal(bucket) > 0)
    .map(
      (bucket) =>
        `<tr><th scope="row">${escape(BUCKET_LABELS[bucket])}</th>${blocks
          .map((b) => cell(b, bucket))
          .join('')}<td class="row-total">${rowTotal(bucket)}</td></tr>`,
    )
    .join('\n        ');

  const perRepoVisible = blocks.map((b) =>
    visibleBuckets.reduce((a, bucket) => a + cellTargets(b, bucket).count, 0),
  );
  const grandTotal = perRepoVisible.reduce((a, b) => a + b, 0);
  const hiddenPer = blocks.map((b) => cellTargets(b, 'hidden'));
  const hiddenTotal = hiddenPer.reduce((a, h) => a + h.count, 0);

  return `<section class="summary">
  <h2>Waiting on you <span class="count">${grandTotal} across ${blocks.length} repo${blocks.length === 1 ? '' : 's'}</span></h2>
  <table class="summary-table">
    <thead>
      <tr><th scope="col">bucket</th>${blocks
        .map(
          (b) =>
            `<th scope="col"><a href="#${repoAnchor(b.repo)}">${escape(b.repo.split('/')[1] ?? b.repo)}</a></th>`,
        )
        .join('')}<th scope="col">total</th></tr>
    </thead>
    <tbody>
        ${rows}
    </tbody>
    <tfoot>
      <tr class="grand"><th scope="row">total</th>${perRepoVisible
        .map((n) => `<td>${n}</td>`)
        .join('')}<td class="row-total">${grandTotal}</td></tr>
      <tr class="excluded"><th scope="row">${escape(BUCKET_LABELS.hidden)}<span class="note"> (excluded)</span></th>${blocks
        .map((b) => cell(b, 'hidden'))
        .join('')}<td class="row-total">${hiddenTotal}</td></tr>
    </tfoot>
  </table>
</section>`;
}

function renderRepoBlock(
  block: RepoBlock,
  viewer: string,
  now: Date,
  counts: Map<string, number> | undefined,
): string {
  const repoUrl = `https://github.com/${block.repo}`;
  const inner =
    block.priorityGroups.length > 0
      ? block.priorityGroups
          .map((g) => renderPriorityGroup(g, block.repo, viewer, now, counts ?? new Map()))
          .join('\n  ')
      : block.sections
          .map((s) => renderSection(s, block.repo, '', viewer, now, counts ?? new Map()))
          .join('\n  ');
  return `<section class="repo" id="${repoAnchor(block.repo)}">
  <h2><a href="${escape(repoUrl)}" ${NEW_TAB}>${escape(block.repo)}</a> <span class="count">${block.visibleCount} / ${block.totalCount} visible</span></h2>
  ${inner}
</section>`;
}

function renderPriorityGroup(
  group: PriorityGroup,
  repo: string,
  viewer: string,
  now: Date,
  counts: Map<string, number>,
): string {
  const sections = group.sections
    .map((s) => renderSection(s, repo, group.label, viewer, now, counts))
    .join('\n    ');
  return `<details class="priority-group" open>
    <summary class="priority-label">${escape(group.label)} <span class="count">${group.visibleCount} / ${group.totalCount} visible</span></summary>
    ${sections}
  </details>`;
}

// Shared `<colgroup>` so every bucket-section table within a repo renders
// with identical column widths. Combined with `table-layout: fixed` in the
// CSS, this is what keeps the #/diff/title/author/flags/age columns lined
// up across the per-bucket tables — without it, each table sizes its
// columns independently based on its own content.
const COLGROUP = `<colgroup>
        <col class="col-num">
        <col class="col-diff">
        <col class="col-title">
        <col class="col-issue">
        <col class="col-author">
        <col class="col-flags">
        <col class="col-age">
      </colgroup>`;

function renderSection(
  section: BucketSection,
  repo: string,
  group: string,
  viewer: string,
  now: Date,
  counts: Map<string, number>,
): string {
  const expanded = BUCKETS_EXPANDED_BY_DEFAULT.has(section.bucket) ? ' open' : '';
  const label = BUCKET_LABELS[section.bucket];
  const description = BUCKET_DESCRIPTIONS[section.bucket];
  const count = section.prs.length;
  const isHidden = section.bucket === 'hidden';
  // Last column is "flags" for actionable buckets, "reason" for hidden ones
  // (why the row isn't surfaced). Same column position so widths align.
  const lastHeader = isHidden ? 'reason' : 'flags';
  const rows = section.prs.map((c) => renderRow(c, viewer, now, counts)).join('\n      ');
  return `<details class="bucket bucket-${section.bucket}" id="${sectionAnchor(repo, group, section.bucket)}"${expanded}>
    <summary>${escape(label)} <span class="count">(${count})</span></summary>
    <p class="bucket-desc">${escape(description)}</p>
    <table class="pr-table">
      ${COLGROUP}
      <thead><tr><th>#</th><th>diff</th><th>title</th><th>issue</th><th>author</th><th>${lastHeader}</th><th>age</th></tr></thead>
      <tbody>
      ${rows}
      </tbody>
    </table>
  </details>`;
}

function renderRow(
  c: ClassifiedPR,
  viewer: string,
  now: Date,
  counts: Map<string, number>,
): string {
  const pr = c.pr;
  const diff = renderDiff(pr);
  const author = pr.author?.login ?? '(unknown)';
  const openCount = counts.get(author) ?? 1;
  const authorTag = author === viewer ? ' <span class="role-tag">you</span>' : '';
  const lastCell =
    c.bucket === 'hidden'
      ? (c.reasons.length > 0 ? c.reasons : ['unknown']).map(renderHideReason).join(' ')
      : c.flags.map(renderFlag).join(' ');
  const age = formatAge(pr, now);
  return `<tr>
        <td><a href="${escape(pr.url)}" ${NEW_TAB}>#${pr.number}</a></td>
        <td>${diff}</td>
        <td>${escape(pr.title)}</td>
        <td>${renderIssueCell(pr)}</td>
        <td><a href="https://github.com/${escape(author)}" ${NEW_TAB}>@${escape(author)}</a>${authorTag} <span class="open-count">[${openCount} open]</span></td>
        <td>${lastCell}</td>
        <td>${escape(age)}</td>
      </tr>`;
}

// Per-class breakdown instead of one total. Only non-zero classes render, so a
// pure source change stays as short as it was before, while a fixture drop is
// visibly a fixture drop. Source leads because it is the sort key.
const CLASS_ABBREV: Record<FileClass, string> = {
  source: 'src',
  tests: 'test',
  fixtures: 'fix',
  docs: 'doc',
  config: 'cfg',
  generated: 'gen',
};

function renderDiff(pr: PullRequest): string {
  const comp = computeComposition(pr);
  if (!comp.exact) {
    // No per-file data (cached before fileStats existed). Show the whole-PR
    // total rather than a breakdown we cannot stand behind.
    return `<span class="diff">${addDel(pr.additions, pr.deletions)}</span>`;
  }
  const rows = FILE_CLASSES.filter((cls) => {
    const t = comp.byClass[cls];
    return t.additions + t.deletions > 0;
  }).map((cls) => {
    const t = comp.byClass[cls];
    const tip = `${t.files} ${cls} file${t.files === 1 ? '' : 's'}: +${t.additions} / -${t.deletions}`;
    return (
      `<span class="dc-label dc-${cls}" data-tip="${escape(tip)}">${CLASS_ABBREV[cls]}</span>` +
      `<span class="dc-nums">${addDel(t.additions, t.deletions)}</span>`
    );
  });
  if (rows.length === 0) return '<span class="dim">—</span>';
  if (comp.truncated) {
    rows.push(
      `<span class="dc-label dc-trunc" data-tip="More than 100 files changed; this split covers the first 100 only.">+…</span><span class="dc-nums"></span>`,
    );
  }
  return `<div class="diff dcs">${rows.join('')}</div>`;
}

function addDel(additions: number, deletions: number): string {
  return `<span class="add">+${additions}</span>/<span class="del">-${deletions}</span>`;
}

// The issues this PR claims to close, plus the other open PRs claiming the
// same ones. Naming those PRs rather than only counting them is what makes the
// row actionable: three separate contributors each fixed jaeger#8780, and
// deciding which to keep means opening the other two.
function renderIssueCell(pr: PullRequest): string {
  const refs = pr.computed?.issueRefs ?? [];
  if (refs.length === 0) return '<span class="dim">—</span>';
  const meta = pr.computed?.issueMeta ?? {};
  const links = refs
    .map((ref) => {
      const key = refKey(ref);
      const m = meta[key];
      const label = sameRepoLabel(ref, pr) ?? key;
      const cls = m?.state && m.state !== 'OPEN' ? 'issue-link closed' : 'issue-link';
      const tip = m
        ? `${m.isPullRequest ? 'PR' : 'Issue'} ${key} (${m.state.toLowerCase()})${m.author ? `, opened by @${m.author}` : ''}: ${m.title}`
        : `${key} — could not be resolved`;
      return `<a class="${cls}" href="${escape(issueUrl(ref))}" ${NEW_TAB} data-tip="${escape(tip)}">${escape(label)}</a>`;
    })
    .join(' ');

  const others = (pr.computed?.collidingPrs ?? [])
    .map(parseRefKey)
    .filter((r): r is NonNullable<typeof r> => r !== null)
    .sort((a, b) => a.number - b.number);
  if (others.length === 0) return links;

  const otherLinks = others
    .map((r) => {
      const label = sameRepoLabel(r, pr) ?? refKey(r);
      const url = `https://github.com/${r.owner}/${r.repo}/pull/${r.number}`;
      return `<a href="${escape(url)}" ${NEW_TAB}>${escape(label)}</a>`;
    })
    .join(', ');
  return `${links}<span class="issue-others">other PRs: ${otherLinks}</span>`;
}

// Bare `#N` when the reference points into the PR's own repo, fully qualified
// otherwise, so a cross-repo reference is never mistaken for a local one.
function sameRepoLabel(ref: { owner: string; repo: string; number: number }, pr: PullRequest) {
  return ref.owner === pr.repo.owner && ref.repo === pr.repo.name ? `#${ref.number}` : null;
}

// One-sentence explanation of what each flag/hide-reason chip means, shown
// as a CSS hover tooltip (see `.flag[data-tip]` below) so a reader doesn't
// have to know the classifier internals to interpret a pill. A plain
// `title` attribute would work too, but browsers gate it behind a ~1-2s
// hover delay we can't override; the CSS tooltip shows immediately. Keyed
// by the chip's displayed
// head text (see `renderFlag` and `renderHideReason` below) — both the
// visible-row flags and the hidden-bucket reasons share this map since
// several (e.g. `MERGE-CONFLICT`) name the same underlying predicate.
const FLAG_DESCRIPTIONS: Record<string, string> = {
  DRAFT: 'Author opened this PR as a draft — not yet marked ready for review.',
  BOT: 'Opened by a bot account that is not a recognized dependency-update bot.',
  'BOT-AUTHORED': 'Opened by a bot account that is not a recognized dependency-update bot.',
  BLOCKER: 'Carries a `release-blocker` or `blocker` label.',
  'MERGE-CONFLICT':
    'Branch has merge conflicts with the base branch — needs a rebase before it can be reviewed.',
  STALE: 'Carries the `stale` label, or the author has gone silent past the configured threshold.',
  'STALE-ON-AUTHOR':
    'Carries the `stale` label, or the author has gone silent past the configured threshold.',
  QUESTION:
    'Carries the `awaiting-maintainer-input` label — the author is waiting on a maintainer to answer something.',
  'WAITING-FOR-AUTHOR':
    'Carries the `waiting-for-author` label — the ball is in the author’s court.',
  'NEEDS-LABEL':
    'CI is failing only on a label-gate check (e.g. a missing changelog/kind label) — otherwise mergeable.',
  'NO-ISSUE':
    'PR description does not reference a linked issue via `Fixes #N` / `Closes #N` / `Resolves #N`.',
  'NO-TESTS': 'Source files changed, but no test files were added or modified alongside them.',
  UNRESOLVED:
    'An unresolved review thread exists and the author has pushed new commits since the last reviewer comment.',
  'UNRESOLVED-FROM-REVIEWER':
    'An unresolved review thread exists and the author has pushed new commits since the last reviewer comment.',
  'RESOLVED-W/O-REPLY':
    'The author resolved one or more review threads without replying to the reviewer’s last comment first.',
  'DCO-MISSING': 'One or more non-merge commits are missing a `Signed-off-by` trailer.',
  'CI-FAILING': 'CI status rollup is failing on checks beyond just a label gate.',
  'DESCRIPTION-EMPTY': 'PR description is empty or contains only unfilled template stubs.',
  'QUOTA-EXCEEDED':
    'Author has reached the new-contributor open-PR quota; this PR is on hold until an older one closes.',
  'ISSUE-COLLISION':
    'Another open PR claims to close the same issue. The count includes this PR, so `2` means one other PR is duplicating the work.',
  'SELF-FILED':
    'The author of this PR also opened the issue it closes — often a manufactured task rather than a problem the project had already identified. Not applied to maintainers or interns.',
  'ISSUE-CLOSED':
    'The issue this PR claims to close is already closed, so the PR is likely superseded or stale.',
};

function tipAttr(head: string): string {
  const tooltip = FLAG_DESCRIPTIONS[head];
  return tooltip ? ` data-tip="${escape(tooltip)}"` : '';
}

// Render one row flag. CSS class is the alphanumeric+dash prefix of the
// label (everything before the first colon) with non-class-safe chars
// rewritten to `-` — so `RESOLVED-W/O-REPLY: 3` displays the full label
// but uses `flag-RESOLVED-W-O-REPLY` as its class.
function renderFlag(label: string): string {
  const head = (label.split(':')[0] ?? label).trim();
  const cls = head.replace(/[^A-Za-z0-9-]/g, '-');
  return `<span class="flag flag-${cls}"${tipAttr(head)}>${escape(label)}</span>`;
}

// Renders the classifier's hide reason as a small neutral chip. Reasons
// come from the bucket classifier in one of three forms:
//   - `draft`              -> author opened it as a draft
//   - `bot-authored`       -> non-dependency bot author
//   - `hide:<predicate_id>` -> a predicate with hidesFromTriage=true fired
// Normalize to a SHORT-DASH-CASE label.
function renderHideReason(raw: string): string {
  const stripped = raw.startsWith('hide:') ? raw.slice(5) : raw;
  const label = stripped.replace(/_/g, '-').toUpperCase();
  return `<span class="flag flag-HIDE"${tipAttr(label)}>${escape(label)}</span>`;
}

// Inline favicon: a white funnel (the triage metaphor — many PRs in, a
// narrow stream out) on an amber tile, matching the "review-requested"
// bucket accent. SVG works in every modern browser and stays tiny even
// base64-encoded (~300 bytes), so the HTML report keeps its self-contained
// property.
const FAVICON_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">
<rect width="16" height="16" rx="3" fill="#d29922"/>
<path d="M2.5 3 L13.5 3 L9.5 8 L9.5 13 L6.5 13 L6.5 8 Z" fill="white"/>
</svg>`;
const FAVICON_DATA_URL = `data:image/svg+xml;base64,${Buffer.from(FAVICON_SVG).toString('base64')}`;

const CSS = `
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; max-width: 1200px; margin: 2em auto; padding: 0 1em; color: #1f2328; line-height: 1.4; }
  header h1 { margin: 0 0 0.2em 0; }
  header .meta { color: #57606a; font-size: 0.9em; margin-bottom: 0.8em; }
  header .toolbar { margin-bottom: 1.5em; }
  header .toolbar button { font-size: 0.85em; padding: 0.35em 0.8em; margin-right: 0.5em; border: 1px solid #d0d7de; border-radius: 6px; background: white; color: #1f2328; cursor: pointer; }
  header .toolbar button:hover { background: #f6f8fa; }
  section.repo { margin: 2em 0; }
  section.repo > h2 { border-bottom: 1px solid #d0d7de; padding-bottom: 0.3em; }
  section.repo .count { font-weight: normal; color: #57606a; font-size: 0.85em; }
  details.priority-group { margin: 1em 0; border: 1px solid #d0d7de; border-radius: 6px; padding: 0 0.8em 0.5em 0.8em; }
  details.priority-group > summary.priority-label { cursor: pointer; padding: 0.4em 0; font-weight: 700; font-size: 1em; list-style: none; }
  details.priority-group > summary.priority-label .count { font-weight: normal; color: #57606a; font-size: 0.85em; }
  details.bucket { margin: 0.5em 0; border-left: 3px solid #d0d7de; padding-left: 0.8em; }
  details.bucket-review-requested-on-you { border-left-color: #d29922; }
  details.bucket-changes-requested-revised { border-left-color: #a40e26; }
  details.bucket-youre-the-bottleneck { border-left-color: #cf222e; }
  details.bucket-high-trust-awaiting-first-response { border-left-color: #1f883d; }
  details.bucket-first-timer-awaiting { border-left-color: #8250df; }
  details.bucket-codeowners-hits, details.bucket-fyi, details.bucket-dependency-bots, details.bucket-hidden { border-left-color: #d0d7de; }
  summary { cursor: pointer; padding: 0.3em 0; font-weight: 600; }
  summary .count { font-weight: normal; color: #57606a; }
  p.bucket-desc { margin: 0 0 0.6em 0; color: #57606a; font-size: 0.85em; }
  /* table-layout: fixed + <col> widths keep columns aligned across every
     per-bucket table in a repo. Without this, each table would size its
     own columns based on its content and rows wouldn't line up vertically. */
  table.pr-table { border-collapse: collapse; width: 100%; margin: 0.5em 0 1em 0; font-size: 0.9em; table-layout: fixed; }
  table.pr-table .col-num    { width: 5em; }
  table.pr-table .col-diff   { width: 9.5em; }
  table.pr-table .col-title  { width: auto; }
  table.pr-table .col-issue  { width: 9.5em; }
  table.pr-table .col-author { width: 13em; }
  table.pr-table .col-flags  { width: 11em; }
  table.pr-table .col-age    { width: 4em; }
  /* word-break lets long titles wrap inside the fixed-width title column
     instead of overflowing. */
  th, td { padding: 0.3em 0.5em; text-align: left; vertical-align: top; word-wrap: break-word; word-break: break-word; }
  thead { color: #57606a; font-size: 0.85em; }
  tbody tr { border-top: 1px solid #eaeef2; }
  tbody tr:hover { background: #f6f8fa; }
  td a { color: #0969da; text-decoration: none; }
  td a:hover { text-decoration: underline; }
  .diff .add { color: #1f883d; }
  .diff .del { color: #cf222e; }
  /* One row per file class, each keeping the familiar +added/-deleted pair.
     Two-column grid so the labels and the counts line up down the cell.
     Only the source label gets ink — it is the number the bucket sorts by. */
  .dcs { display: grid; grid-template-columns: max-content max-content; column-gap: 0.45em; font-size: 0.9em; font-variant-numeric: tabular-nums; }
  .dcs .dc-label { color: #8c959f; }
  .dcs .dc-source { color: #1f2328; font-weight: 600; }
  .dcs .dc-nums { white-space: nowrap; }
  .dim { color: #8c959f; }
  /* Top-of-report bucket-by-repo matrix. */
  section.summary { margin: 0 0 1.6em 0; }
  section.summary h2 { font-size: 1.05em; margin: 0 0 0.5em 0; border: none; padding: 0; }
  table.summary-table { border-collapse: collapse; font-size: 0.9em; font-variant-numeric: tabular-nums; }
  table.summary-table th, table.summary-table td { padding: 0.3em 0.9em 0.3em 0; text-align: right; }
  table.summary-table th[scope="row"] { text-align: left; font-weight: normal; padding-right: 1.6em; }
  table.summary-table thead th { color: #57606a; font-size: 0.85em; font-weight: normal; border-bottom: 1px solid #d0d7de; }
  table.summary-table tbody tr:hover { background: #f6f8fa; }
  table.summary-table .row-total { font-weight: 600; }
  table.summary-table tfoot .grand th, table.summary-table tfoot .grand td { border-top: 1px solid #d0d7de; font-weight: 600; }
  table.summary-table tfoot .excluded th, table.summary-table tfoot .excluded td { color: #8c959f; font-weight: normal; }
  table.summary-table .note { font-size: 0.85em; }
  table.summary-table td a { color: #0969da; text-decoration: none; }
  table.summary-table td a:hover { text-decoration: underline; }
  table.summary-table thead th a { color: inherit; text-decoration: none; }
  table.summary-table thead th a:hover { text-decoration: underline; }
  /* Briefly tint a section jumped to from the summary, so it is obvious which
     table the click landed on. */
  .bucket:target > summary, section.repo:target > h2 { background: #fff8c5; }
  a.issue-link.closed { color: #8250df; text-decoration: line-through; }
  .issue-others { display: block; font-size: 0.85em; color: #57606a; margin-top: 0.15em; }
  .issue-others a { color: #57606a; }
  .role-tag { font-size: 0.7em; background: #ddf4ff; color: #0969da; padding: 0.05em 0.4em; border-radius: 3px; vertical-align: middle; }
  .open-count { color: #57606a; font-size: 0.85em; }
  .flag { font-size: 0.7em; padding: 0.1em 0.4em; border-radius: 3px; background: #eaeef2; margin-right: 0.2em; }
  /* Custom hover tooltip instead of the native "title" attribute — the
     browser's built-in tooltip only appears after a ~1-2s hover delay we
     can't override; this one shows as soon as the mouse enters the pill. */
  [data-tip] { cursor: help; position: relative; }
  [data-tip]:hover::after {
    content: attr(data-tip);
    position: absolute;
    bottom: 125%;
    left: 50%;
    transform: translateX(-50%);
    z-index: 10;
    width: max-content;
    max-width: 260px;
    padding: 0.4em 0.6em;
    border-radius: 4px;
    background: #1f2328;
    color: white;
    font-weight: normal;
    font-size: 1em;
    line-height: 1.3;
    white-space: normal;
    box-shadow: 0 2px 6px rgba(0, 0, 0, 0.25);
    pointer-events: none;
  }
  .flag-ISSUE-COLLISION { background: #cf222e; color: white; }
  .flag-SELF-FILED { background: #fff1e5; color: #953800; }
  .flag-ISSUE-CLOSED { background: #f5e8ff; color: #8250df; }
  .flag-BLOCKER { background: #cf222e; color: white; }
  .flag-MERGE-CONFLICT { background: #ffebe9; color: #82071e; }
  .flag-STALE { background: #fff8c5; color: #66533d; }
  .flag-QUESTION { background: #ddf4ff; color: #0550ae; }
  .flag-POSSIBLE-QUESTION { background: #fff1e5; color: #66533d; }
  .flag-DRAFT, .flag-BOT, .flag-HIDE { background: #eaeef2; color: #57606a; }
  /* P3 advisory flags — distinct muted tones so the column is scannable
     but the flags don't compete with BLOCKER/MERGE-CONFLICT for attention. */
  .flag-NEEDS-LABEL { background: #ddf4ff; color: #0550ae; }
  .flag-WAITING-FOR-AUTHOR { background: #fff8c5; color: #66533d; }
  .flag-NO-ISSUE { background: #fff1e5; color: #66533d; }
  .flag-NO-TESTS { background: #fff1e5; color: #66533d; }
  .flag-UNRESOLVED { background: #fff8c5; color: #66533d; }
  .flag-RESOLVED-W-O-REPLY { background: #ffebe9; color: #82071e; }
  footer { margin-top: 4em; color: #8b949e; font-size: 0.8em; border-top: 1px solid #eaeef2; padding-top: 1em; }
`;

const ESCAPE_MAP: Record<string, string> = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#39;',
};

function escape(s: string): string {
  return String(s).replace(/[&<>"']/g, (c) => ESCAPE_MAP[c] ?? c);
}
