// Self-contained HTML triage report. No external assets, all CSS inline,
// double-clickable from the desktop.
//
// Layout: repo first, then (optionally) priority groups, then bucket sections.
// Per the RFC, the four high-signal buckets default expanded; CODEOWNERS/FYI/
// Hidden default collapsed. Empty buckets are omitted entirely.

import {
  BUCKETS_EXPANDED_BY_DEFAULT,
  BUCKET_DESCRIPTIONS,
  BUCKET_LABELS,
  type Bucket,
  type ClassifiedPR,
} from '../buckets.js';
import {
  type BucketSection,
  formatAge,
  groupByRepo,
  type PriorityGroup,
  type RepoBlock,
} from './shared.js';

export interface RenderOptions {
  viewer: string;
  now: Date;
  authorOpenCounts: Map<string, Map<string, number>>; // repo -> author -> count
  priorityLabels?: string[];
}

export function renderHtml(classified: ClassifiedPR[], opts: RenderOptions): string {
  const blocks = groupByRepo(classified, opts.priorityLabels);
  const date = opts.now.toISOString().slice(0, 16).replace('T', ' ');

  const body = blocks
    .map((b) => renderRepoBlock(b, opts.viewer, opts.now, opts.authorOpenCounts.get(b.repo)))
    .join('\n');

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>PR Triage — ${escape(date)} — @${escape(opts.viewer)}</title>
<link rel="icon" type="image/svg+xml" href="${FAVICON_DATA_URL}">
<style>${CSS}</style>
</head>
<body>
<header>
  <h1>PR Triage</h1>
  <div class="meta">${escape(date)} UTC &middot; @${escape(opts.viewer)}</div>
</header>
${body}
<footer>Generated by <code>maintainer-tools triage</code>.</footer>
</body>
</html>
`;
}

function renderRepoBlock(
  block: RepoBlock,
  viewer: string,
  now: Date,
  counts: Map<string, number> | undefined,
): string {
  const repoUrl = `https://github.com/${block.repo}`;
  const inner =
    block.priorityGroups.length > 0
      ? block.priorityGroups
          .map((g) => renderPriorityGroup(g, viewer, now, counts ?? new Map()))
          .join('\n  ')
      : block.sections.map((s) => renderSection(s, viewer, now, counts ?? new Map())).join('\n  ');
  return `<section class="repo">
  <h2><a href="${repoUrl}">${escape(block.repo)}</a> <span class="count">${block.visibleCount} / ${block.totalCount} visible</span></h2>
  ${inner}
</section>`;
}

function renderPriorityGroup(
  group: PriorityGroup,
  viewer: string,
  now: Date,
  counts: Map<string, number>,
): string {
  const sections = group.sections.map((s) => renderSection(s, viewer, now, counts)).join('\n    ');
  return `<details class="priority-group" open>
    <summary class="priority-label">${escape(group.label)} <span class="count">${group.visibleCount} / ${group.totalCount} visible</span></summary>
    ${sections}
  </details>`;
}

// Shared `<colgroup>` so every bucket-section table within a repo renders
// with identical column widths. Combined with `table-layout: fixed` in the
// CSS, this is what keeps the #/diff/title/author/flags/age columns lined
// up across the per-bucket tables — without it, each table sizes its
// columns independently based on its own content.
const COLGROUP = `<colgroup>
        <col class="col-num">
        <col class="col-diff">
        <col class="col-title">
        <col class="col-author">
        <col class="col-flags">
        <col class="col-age">
      </colgroup>`;

function renderSection(
  section: BucketSection,
  viewer: string,
  now: Date,
  counts: Map<string, number>,
): string {
  const expanded = BUCKETS_EXPANDED_BY_DEFAULT.has(section.bucket) ? ' open' : '';
  const label = BUCKET_LABELS[section.bucket];
  const description = BUCKET_DESCRIPTIONS[section.bucket];
  const count = section.prs.length;
  const isHidden = section.bucket === 'hidden';
  // Last column is "flags" for actionable buckets, "reason" for hidden ones
  // (why the row isn't surfaced). Same column position so widths align.
  const lastHeader = isHidden ? 'reason' : 'flags';
  const rows = section.prs.map((c) => renderRow(c, viewer, now, counts)).join('\n      ');
  return `<details class="bucket bucket-${section.bucket}"${expanded}>
    <summary>${escape(label)} <span class="count">(${count})</span></summary>
    <p class="bucket-desc">${escape(description)}</p>
    <table class="pr-table">
      ${COLGROUP}
      <thead><tr><th>#</th><th>diff</th><th>title</th><th>author</th><th>${lastHeader}</th><th>age</th></tr></thead>
      <tbody>
      ${rows}
      </tbody>
    </table>
  </details>`;
}

function renderRow(
  c: ClassifiedPR,
  viewer: string,
  now: Date,
  counts: Map<string, number>,
): string {
  const pr = c.pr;
  const diff = `<span class="diff"><span class="add">+${pr.additions}</span>/<span class="del">-${pr.deletions}</span></span>`;
  const author = pr.author?.login ?? '(unknown)';
  const openCount = counts.get(author) ?? 1;
  const authorTag = author === viewer ? ' <span class="role-tag">you</span>' : '';
  const lastCell =
    c.bucket === 'hidden'
      ? renderHideReason(c.reasons[0] ?? 'unknown')
      : c.flags.map(renderFlag).join(' ');
  const age = formatAge(pr, now);
  return `<tr>
        <td><a href="${pr.url}">#${pr.number}</a></td>
        <td>${diff}</td>
        <td>${escape(pr.title)}</td>
        <td><a href="https://github.com/${escape(author)}">@${escape(author)}</a>${authorTag} <span class="open-count">[${openCount} open]</span></td>
        <td>${lastCell}</td>
        <td>${escape(age)}</td>
      </tr>`;
}

// Render one row flag. CSS class is the alphanumeric+dash prefix of the
// label (everything before the first colon) with non-class-safe chars
// rewritten to `-` — so `RESOLVED-W/O-REPLY: 3` displays the full label
// but uses `flag-RESOLVED-W-O-REPLY` as its class.
function renderFlag(label: string): string {
  const head = (label.split(':')[0] ?? label).trim();
  const cls = head.replace(/[^A-Za-z0-9-]/g, '-');
  return `<span class="flag flag-${cls}">${escape(label)}</span>`;
}

// Renders the classifier's hide reason as a small neutral chip. Reasons
// come from the bucket classifier in one of three forms:
//   - `draft`              -> author opened it as a draft
//   - `bot-authored`       -> non-dependency bot author
//   - `hide:<predicate_id>` -> a predicate with hidesFromTriage=true fired
// Normalize to a SHORT-DASH-CASE label.
function renderHideReason(raw: string): string {
  const stripped = raw.startsWith('hide:') ? raw.slice(5) : raw;
  const label = stripped.replace(/_/g, '-').toUpperCase();
  return `<span class="flag flag-HIDE">${escape(label)}</span>`;
}

// Inline favicon: a white funnel (the triage metaphor — many PRs in, a
// narrow stream out) on an amber tile, matching the "review-requested"
// bucket accent. SVG works in every modern browser and stays tiny even
// base64-encoded (~300 bytes), so the HTML report keeps its self-contained
// property.
const FAVICON_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">
<rect width="16" height="16" rx="3" fill="#d29922"/>
<path d="M2.5 3 L13.5 3 L9.5 8 L9.5 13 L6.5 13 L6.5 8 Z" fill="white"/>
</svg>`;
const FAVICON_DATA_URL = `data:image/svg+xml;base64,${Buffer.from(FAVICON_SVG).toString('base64')}`;

const CSS = `
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; max-width: 1200px; margin: 2em auto; padding: 0 1em; color: #1f2328; line-height: 1.4; }
  header h1 { margin: 0 0 0.2em 0; }
  header .meta { color: #57606a; font-size: 0.9em; margin-bottom: 1.5em; }
  section.repo { margin: 2em 0; }
  section.repo > h2 { border-bottom: 1px solid #d0d7de; padding-bottom: 0.3em; }
  section.repo .count { font-weight: normal; color: #57606a; font-size: 0.85em; }
  details.priority-group { margin: 1em 0; border: 1px solid #d0d7de; border-radius: 6px; padding: 0 0.8em 0.5em 0.8em; }
  details.priority-group > summary.priority-label { cursor: pointer; padding: 0.4em 0; font-weight: 700; font-size: 1em; list-style: none; }
  details.priority-group > summary.priority-label .count { font-weight: normal; color: #57606a; font-size: 0.85em; }
  details.bucket { margin: 0.5em 0; border-left: 3px solid #d0d7de; padding-left: 0.8em; }
  details.bucket-review-requested-on-you { border-left-color: #d29922; }
  details.bucket-youre-the-bottleneck { border-left-color: #cf222e; }
  details.bucket-high-trust-awaiting-first-response { border-left-color: #1f883d; }
  details.bucket-first-timer-awaiting { border-left-color: #8250df; }
  details.bucket-codeowners-hits, details.bucket-fyi, details.bucket-dependency-bots, details.bucket-hidden { border-left-color: #d0d7de; }
  summary { cursor: pointer; padding: 0.3em 0; font-weight: 600; }
  summary .count { font-weight: normal; color: #57606a; }
  p.bucket-desc { margin: 0 0 0.6em 0; color: #57606a; font-size: 0.85em; }
  /* table-layout: fixed + <col> widths keep columns aligned across every
     per-bucket table in a repo. Without this, each table would size its
     own columns based on its content and rows wouldn't line up vertically. */
  table.pr-table { border-collapse: collapse; width: 100%; margin: 0.5em 0 1em 0; font-size: 0.9em; table-layout: fixed; }
  table.pr-table .col-num    { width: 5em; }
  table.pr-table .col-diff   { width: 7em; }
  table.pr-table .col-title  { width: auto; }
  table.pr-table .col-author { width: 14em; }
  table.pr-table .col-flags  { width: 11em; }
  table.pr-table .col-age    { width: 4em; }
  /* word-break lets long titles wrap inside the fixed-width title column
     instead of overflowing. */
  th, td { padding: 0.3em 0.5em; text-align: left; vertical-align: top; word-wrap: break-word; word-break: break-word; }
  thead { color: #57606a; font-size: 0.85em; }
  tbody tr { border-top: 1px solid #eaeef2; }
  tbody tr:hover { background: #f6f8fa; }
  td a { color: #0969da; text-decoration: none; }
  td a:hover { text-decoration: underline; }
  .diff .add { color: #1f883d; }
  .diff .del { color: #cf222e; }
  .role-tag { font-size: 0.7em; background: #ddf4ff; color: #0969da; padding: 0.05em 0.4em; border-radius: 3px; vertical-align: middle; }
  .open-count { color: #57606a; font-size: 0.85em; }
  .flag { font-size: 0.7em; padding: 0.1em 0.4em; border-radius: 3px; background: #eaeef2; margin-right: 0.2em; }
  .flag-BLOCKER { background: #cf222e; color: white; }
  .flag-MERGE-CONFLICT { background: #ffebe9; color: #82071e; }
  .flag-STALE { background: #fff8c5; color: #66533d; }
  .flag-QUESTION { background: #ddf4ff; color: #0550ae; }
  .flag-POSSIBLE-QUESTION { background: #fff1e5; color: #66533d; }
  .flag-DRAFT, .flag-BOT, .flag-HIDE { background: #eaeef2; color: #57606a; }
  /* P3 advisory flags — distinct muted tones so the column is scannable
     but the flags don't compete with BLOCKER/MERGE-CONFLICT for attention. */
  .flag-NEEDS-LABEL { background: #ddf4ff; color: #0550ae; }
  .flag-WAITING-FOR-AUTHOR { background: #fff8c5; color: #66533d; }
  .flag-NO-ISSUE { background: #fff1e5; color: #66533d; }
  .flag-NO-TESTS { background: #fff1e5; color: #66533d; }
  .flag-UNRESOLVED { background: #fff8c5; color: #66533d; }
  .flag-RESOLVED-W-O-REPLY { background: #ffebe9; color: #82071e; }
  footer { margin-top: 4em; color: #8b949e; font-size: 0.8em; border-top: 1px solid #eaeef2; padding-top: 1em; }
`;

const ESCAPE_MAP: Record<string, string> = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#39;',
};

function escape(s: string): string {
  return String(s).replace(/[&<>"']/g, (c) => ESCAPE_MAP[c] ?? c);
}
