// Self-contained HTML nudge report. Renders each PR's would-be digest
// comment as GitHub-flavored markdown so the maintainer can preview exactly
// what contributors will see.

export interface NudgeEntry {
  repo: string;
  prNumber: number;
  prTitle: string;
  prUrl: string;
  author: string | null;
  body: string;
}

export interface NudgeRenderOptions {
  now: Date;
}

export function renderNudgeHtml(entries: NudgeEntry[], opts: NudgeRenderOptions): string {
  const date = opts.now.toISOString().slice(0, 16).replace('T', ' ');
  const cards = entries.map(renderCard).join('\n');
  const count = entries.length;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Nudge Dry-Run — ${escape(date)}</title>
<style>${CSS}</style>
</head>
<body>
<header>
  <h1>Nudge Dry-Run Preview</h1>
  <div class="meta">${escape(date)} UTC &middot; ${count} PR(s) would be nudged</div>
</header>
<main>
${cards}
</main>
<footer>Generated by <code>maintainer-tools nudge</code>.</footer>
</body>
</html>
`;
}

function renderCard(entry: NudgeEntry): string {
  const author = entry.author ? `@${escape(entry.author)}` : '(unknown)';
  const bodyHtml = markdownToHtml(entry.body);
  return `<article class="nudge-card">
  <div class="card-header">
    <a href="${escape(entry.prUrl)}" class="pr-link">${escape(entry.repo)}#${entry.prNumber}</a>
    <span class="pr-title">${escape(entry.prTitle)}</span>
    <span class="pr-author">${author}</span>
  </div>
  <div class="comment-body">
${bodyHtml}
  </div>
</article>`;
}

// Minimal markdown→HTML converter: handles what renderDigestBody produces
// (paragraphs, unordered lists, inline code, @mentions). No external deps.
function markdownToHtml(md: string): string {
  const lines = md.split('\n');
  const out: string[] = [];
  let inList = false;

  for (const line of lines) {
    if (line.startsWith('- ')) {
      if (!inList) {
        out.push('<ul>');
        inList = true;
      }
      out.push(`  <li>${inlineFormat(line.slice(2))}</li>`);
    } else {
      if (inList) {
        out.push('</ul>');
        inList = false;
      }
      const trimmed = line.trim();
      if (trimmed === '') {
        continue;
      } else {
        out.push(`<p>${inlineFormat(trimmed)}</p>`);
      }
    }
  }
  if (inList) out.push('</ul>');
  return out.join('\n');
}

function inlineFormat(text: string): string {
  let s = escape(text);
  // Inline code: `...`
  s = s.replace(/`([^`]+)`/g, '<code>$1</code>');
  // @mentions
  s = s.replace(/@([\w-]+(?:\[bot\])?)/g, '<strong>@$1</strong>');
  return s;
}

function escape(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

const CSS = `
:root {
  --bg: #0d1117;
  --fg: #e6edf3;
  --muted: #8b949e;
  --card-bg: #161b22;
  --border: #30363d;
  --link: #58a6ff;
  --code-bg: #1f2937;
  --green: #3fb950;
  --red: #f85149;
}
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
  font-size: 14px;
  line-height: 1.5;
  background: var(--bg);
  color: var(--fg);
  padding: 2rem;
  max-width: 900px;
  margin: 0 auto;
}
header { margin-bottom: 2rem; }
h1 { font-size: 1.5rem; margin-bottom: 0.25rem; }
.meta { color: var(--muted); font-size: 0.85rem; }
.nudge-card {
  background: var(--card-bg);
  border: 1px solid var(--border);
  border-radius: 6px;
  margin-bottom: 1.5rem;
  overflow: hidden;
}
.card-header {
  padding: 0.75rem 1rem;
  border-bottom: 1px solid var(--border);
  display: flex;
  gap: 1rem;
  align-items: baseline;
  flex-wrap: wrap;
}
.pr-link {
  color: var(--link);
  text-decoration: none;
  font-weight: 600;
  white-space: nowrap;
}
.pr-link:hover { text-decoration: underline; }
.pr-title { flex: 1; min-width: 200px; }
.pr-author { color: var(--muted); white-space: nowrap; }
.comment-body {
  padding: 1rem;
  border-left: 3px solid var(--border);
  margin: 0.75rem 1rem 1rem 1rem;
  border-radius: 3px;
}
.comment-body p { margin-bottom: 0.5rem; }
.comment-body ul { margin: 0.5rem 0; padding-left: 1.5rem; }
.comment-body li { margin-bottom: 0.25rem; }
.comment-body code {
  background: var(--code-bg);
  padding: 0.15em 0.4em;
  border-radius: 3px;
  font-size: 0.9em;
}
footer {
  margin-top: 3rem;
  color: var(--muted);
  font-size: 0.8rem;
  text-align: center;
}
a { color: var(--link); text-decoration: none; }
a:hover { text-decoration: underline; }
`;
